### ISSUE TITLE
Where to put new material?

### ISSUE THREAD

**Issue by dsolovay** [dsolovay/Helix.Docs#1]
In sitecore/Helix.Docs#20, there is consensus on the need for more material on the foundational package principles. However, these are already discussed in some depth in the [Architectural Principles](../tree/7b444e5afbcbfd6da70d3d29f4e43579ee086ff7/helix/principles/architecture-principles) section, and it would be difficult to add introductory material to this section. On the other hand, the material in the [Introduction](../tree/7b444e5afbcbfd6da70d3d29f4e43579ee086ff7/helix/introduction) seems like it could benefit from a rethinking (see Sitecore/Helix.Docs#28).  So, proposing the following approach:

* Rewrite introduction. Scrap discussion of race cars and definitions, and address with a few paragraphs that speak to the reasons why standards for Sitecore architecture are needed, and explains why the Package Principles are a logical fit, but without discussing these in depth (so as to not submerge people in terms like "the granule of release" when they are just starting.
* Add a lengthier section at the end, "Architectural Founadtions" or similar, that goes into the package principles, and perhaps SOLID in some depth, relating them to specific practices discussed earlier in the document. 

This approach will allow a more detailed discussion of the principles, and will also reinforce the practices (e.g. interface templates, role of abstractions in foundation) as they will be placed in a theoretical context.  This section 4 might have additional suporting material, such as references to current writings or source material, FAQs and so forth.

**Comment by dsolovay** [comment]
The relevant SOLID concepts are OCP, which you need to have a strong handle on to understand how the foundation can be abstract, extensible, and stable, and ISP, which is necessary to have a handle on inter-module communication.  But the package principles will be the star of the show.

**Comment by nickwesselman** [comment]
Hey Dan, would you mind moving this issue to the original Helix.Docs repo instead of your fork? It can still be a new issue that references the RFC (i.e. start a new discussion about the Where/How vs the Why).

**Comment by dsolovay** [comment]
Sure thing. I guess I saw this as a place to brainstorm semi-privately, so
I may fine tune this before moving it over, but I get the value of avoiding
fracturing.

**Comment by dsolovay** [comment]
Closing to keep discussions in main fork.
